/** G3 observable protocol: actual UI mutations; imports are fixture setup and read-only evidence. */
import { expect, test, type Page } from '@playwright/test'
async function enter(page: Page, expanded = true) {
  await page.goto('/')
  await page.getByRole('button', { name: 'Start a new project' }).click()
  await page.getByLabel('Project name').fill('Title G3 authoring')
  await page.getByLabel('Resolution').selectOption('720')
  await page.getByRole('button', { name: 'Create project', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Commands' })).toBeVisible()
  await page.evaluate(async (expanded) => {
    const f = '/src/test/titleOwnerFixtures.ts', d = '/src/state/documentStore.ts', t = '/src/state/transportStore.ts', s = '/src/state/titleEditorStore.ts'
    const fixture = await import(f), store = (await import(d)).useDocumentStore, transport = (await import(t)).useTransportStore
    store.getState().setProject(expanded ? fixture.expandedTitleProject() : fixture.legacyTitleProject())
    transport.getState().setSelectedClip('root-text'); transport.getState().setPlayheadFrame(0)
    ;(await import(s)).useTitleEditorStore.getState().select('root-text', ['root-element'])
  }, expanded)
}
async function snapshot(page: Page) {
  return page.evaluate(async () => {
    const d = '/src/state/documentStore.ts', t = '/src/state/transportStore.ts', f = '/src/domain/projectFile.ts'
    const state = (await import(d)).useDocumentStore.getState(), transport = (await import(t)).useTransportStore.getState(), files = await import(f)
    const clip = state.doc.tracks[0].clips[0]
    return { clip, past: state.past.length, future: state.future.length, previewOwner: transport.effectDocumentPreview?.owner ?? null,
      wire: files.serializeProjectFile(files.createProjectFileSnapshot(state.project, [], [])) }
  })
}
test('compact upgrade, elements, static editing and real project undo/redo', async ({ page }, info) => {
  await enter(page, false)
  const before = await snapshot(page)
  await page.getByRole('button', { name: 'Upgrade to title', exact: true }).click()
  await page.getByLabel('Text content', { exact: true }).fill('G3 title 世界')
  await page.getByLabel('Text content', { exact: true }).press('Tab')
  await page.getByRole('button', { name: 'Add rectangle', exact: true }).click()
  await page.getByRole('checkbox', { name: /Rectangle rectangle/ }).check()
  await page.getByTestId('title-opacity').fill('0.5'); await page.getByTestId('title-opacity').press('Tab')
  await page.getByRole('button', { name: 'Move Rectangle backward' }).click()
  const after = await snapshot(page)
  expect(after.past - before.past).toBe(5)
  expect(after.clip.text).toBeUndefined()
  expect(after.clip.title.elements.map((e: { kind: string; opacity: number }) => [e.kind, e.opacity])).toEqual([['rectangle', .5], ['text', .5]])
  await page.screenshot({ path: info.outputPath('elements-1280.png') })
  await page.getByRole('button', { name: 'Commands', exact: true }).click()
  await page.getByRole('searchbox', { name: 'Search commands' }).fill('Undo')
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  expect((await snapshot(page)).clip.title.elements[0].kind).toBe('text')
  await page.getByRole('button', { name: 'Commands', exact: true }).click()
  await page.getByRole('searchbox', { name: 'Search commands' }).fill('Redo')
  await page.getByRole('button', { name: 'Redo', exact: true }).click()
  expect((await snapshot(page)).wire).toBe(after.wire)
})
test('direct manipulation, Escape cancellation and editor-only safe guides', async ({ page }, info) => {
  await enter(page)
  const handle = page.getByRole('button', { name: 'Move title element Text', exact: true })
  await expect(handle).toBeVisible()
  const before = await snapshot(page), bounds = await handle.boundingBox()
  expect(bounds).not.toBeNull()
  await page.mouse.move(bounds!.x + bounds!.width / 2, bounds!.y + bounds!.height / 2)
  await page.mouse.down(); await page.mouse.move(bounds!.x + bounds!.width / 2 + 20, bounds!.y + bounds!.height / 2 + 10, { steps: 4 }); await page.mouse.up()
  const moved = await snapshot(page)
  expect(moved.past).toBe(before.past + 1); expect(moved.clip.title.elements[0].transform.x).toBeGreaterThan(0)
  const next = await handle.boundingBox()
  await page.mouse.move(next!.x + next!.width / 2, next!.y + next!.height / 2); await page.mouse.down(); await page.mouse.move(next!.x + next!.width / 2 + 20, next!.y + next!.height / 2)
  await page.keyboard.press('Escape'); await page.mouse.up()
  expect((await snapshot(page)).wire).toBe(moved.wire)
  await page.getByRole('checkbox', { name: /Safe guides/ }).check()
  expect((await snapshot(page)).wire).toBe(moved.wire)
  await expect(page.getByTestId('title-safe-0.9')).toBeVisible(); await expect(page.getByTestId('title-safe-0.95')).toBeVisible()
  await page.screenshot({ path: info.outputPath('guides-and-handles.png') })
})
test('motion preview, cancellation, Apply and explicit Reapply', async ({ page }, info) => {
  await enter(page)
  await page.getByRole('button', { name: 'Roll / crawl…' }).click()
  const before = await snapshot(page)
  await page.getByRole('button', { name: 'Preview motion', exact: true }).click()
  expect((await snapshot(page)).previewOwner).toBe('title-authoring')
  expect((await snapshot(page)).wire).toBe(before.wire)
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  expect((await snapshot(page)).previewOwner).toBeNull()
  await page.getByRole('button', { name: 'Roll / crawl…' }).click()
  await page.getByRole('button', { name: 'Apply motion', exact: true }).click()
  const applied = await snapshot(page)
  expect(applied.past).toBe(before.past + 1)
  expect(applied.clip.animation.titleTracks[0].keyframes.map((key: { frame: number }) => key.frame)).toEqual([0, 99])
  await page.getByRole('button', { name: 'Roll / crawl…' }).click()
  await expect(page.getByRole('button', { name: 'Reapply motion', exact: true })).toBeDisabled()
  await page.getByRole('checkbox', { name: 'Replace all listed movement tracks' }).check()
  await page.getByLabel('End frame', { exact: true }).fill('90')
  await page.screenshot({ path: info.outputPath('reapply-review.png') })
  await page.getByRole('button', { name: 'Reapply motion', exact: true }).click()
  expect((await snapshot(page)).clip.animation.titleTracks[0].keyframes.map((key: { frame: number }) => key.frame)).toEqual([0, 90])
})
test('unknown font gets an explicit persisted fallback through real controls', async ({ page }, info) => {
  await enter(page)
  await page.evaluate(async () => {
    const d = '/src/state/documentStore.ts', store = (await import(d)).useDocumentStore, project = structuredClone(store.getState().project)
    project.sequences[0].tracks[0].clips[0].title.elements[0].font = { family: 'Missing G3 Face', fallbackFamily: null }
    store.getState().setProject(project)
  })
  await expect(page.locator('.preview-title-status')).toContainText('Title unavailable')
  await page.getByLabel('Explicit font fallback', { exact: true }).selectOption('serif')
  await expect(page.locator('.preview-title-status')).toContainText('explicit serif fallback')
  const saved = await snapshot(page)
  expect(saved.clip.title.elements[0].font).toEqual({ family: 'Missing G3 Face', fallbackFamily: 'serif' })
  await page.evaluate(async (wire) => {
    const d = '/src/state/documentStore.ts', f = '/src/domain/projectFile.ts', p = '/src/test/titleFileBoundaryFixtures.ts'
    ;(await import(d)).useDocumentStore.getState().setProject((await import(p)).titleProjectFromFile((await import(f)).parseProjectFile(wire)))
  }, saved.wire)
  expect((await snapshot(page)).wire).toBe(saved.wire)
  await page.screenshot({ path: info.outputPath('font-fallback-reopened.png') })
})
test('local template save/use/delete retains independent project copies and real IndexedDB data', async ({ page }, info) => {
  await enter(page)
  await page.getByRole('button', { name: 'Save title template…' }).click()
  await page.getByLabel('Template name', { exact: true }).fill('My G3 title')
  await page.getByRole('button', { name: 'Save template', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Save title template' })).not.toBeVisible()
  expect((await snapshot(page)).past).toBe(0)
  await page.evaluate(async () => { const t = '/src/state/transportStore.ts'; (await import(t)).useTransportStore.getState().setPlayheadFrame(200) })
  await page.getByRole('button', { name: 'Title templates', exact: true }).click()
  await page.getByRole('button', { name: 'My G3 title', exact: true }).click()
  await expect(page.locator('.title-template-review')).toContainText('My G3 title')
  await page.screenshot({ path: info.outputPath('template-review.png') })
  await page.getByRole('button', { name: 'Apply template', exact: true }).click()
  const inserted = await snapshot(page)
  expect(inserted.past).toBe(1)
  const ids = await page.evaluate(async () => { const d = '/src/state/documentStore.ts'; return (await import(d)).useDocumentStore.getState().doc.tracks[0].clips.map((clip: { title: { elements: { id: string }[] } }) => clip.title.elements[0].id) })
  expect(new Set(ids).size).toBe(2)
  await page.getByRole('button', { name: 'Title templates', exact: true }).click()
  await page.getByRole('button', { name: 'Delete template My G3 title', exact: true }).click()
  await expect(page.getByRole('button', { name: 'My G3 title', exact: true })).not.toBeVisible()
  expect((await snapshot(page)).wire).toBe(inserted.wire)
})
test('narrow dialog controls stay reachable and project changes invalidate open reviews', async ({ page }, info) => {
  await enter(page)
  await page.getByRole('button', { name: 'Roll / crawl…' }).click()
  // Qualify the modal after resizing; workspace-wide narrow layout remains separately qualified.
  await page.setViewportSize({ width: 720, height: 800 })
  const dialog = page.getByRole('dialog', { name: 'Roll / crawl', exact: true })
  const bounds = await dialog.boundingBox()
  expect(bounds!.x).toBeGreaterThanOrEqual(0); expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(720)
  await expect(page.getByRole('button', { name: 'Apply motion', exact: true })).toBeVisible()
  await page.screenshot({ path: info.outputPath('motion-dialog-720.png') })
  await page.evaluate(async () => { const t = '/src/state/transportStore.ts'; (await import(t)).useTransportStore.getState().setPlayheadFrame(10) })
  await expect(page.getByRole('button', { name: 'Apply motion', exact: true })).toBeDisabled()
  expect((await snapshot(page)).past).toBe(0)
})
