import { expect, test } from '@playwright/test'
import { gradingPixel, gradingProject, gradingSnapshot } from './issue-196-grading-fixtures.js'

test('LUT import, curve points, wheel gestures, keyboard and undo are usable in the Inspector', async ({ page }) => {
  const problems: string[] = []
  page.on('pageerror', (error) => problems.push(error.message))
  page.on('console', (message) => { if (['warning', 'error'].includes(message.type())) problems.push(message.text()) })
  await gradingProject(page)
  const stack = page.getByRole('region', { name: 'Effect stack', exact: true })
  const beforeImport = await gradingSnapshot(page)
  await stack.getByRole('button', { name: 'Add LUT…', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Choose LUT', exact: true })
  await dialog.getByLabel('Local .cube file').setInputFiles({ name: 'Invert red.cube', mimeType: 'text/plain', buffer: Buffer.from('LUT_1D_SIZE 2\n1 0 0\n0 1 1') })
  await expect(dialog.getByRole('button', { name: 'Apply imported LUT' })).toBeVisible()
  expect((await gradingSnapshot(page)).past).toBe(beforeImport.past)
  await dialog.getByRole('button', { name: 'Apply imported LUT' }).click()
  expect((await gradingSnapshot(page)).past).toBe(beforeImport.past + 1)
  await expect(stack.getByRole('button', { name: 'Add LUT…', exact: true })).toBeFocused()
  await expect.poll(() => gradingPixel(page)).toEqual([191, 128, 192, 255])
  await stack.getByRole('button', { name: 'Add RGB curves', exact: true }).click()
  const curves = page.getByLabel('RGB curves controls', { exact: true })
  await curves.getByLabel('Curve channel').selectOption('green')
  await curves.getByRole('spinbutton', { name: 'Point 2 output', exact: true }).fill('0.5')
  await curves.getByRole('spinbutton', { name: 'Point 2 output', exact: true }).press('Enter')
  await expect.poll(() => gradingPixel(page)).toEqual([191, 64, 192, 255])
  await curves.getByRole('button', { name: 'Add curve point' }).click()
  await expect(curves.getByRole('spinbutton', { name: 'Point 2 input', exact: true })).toHaveValue('0.5')
  const point = curves.getByRole('button', { name: /^green point 2,/ })
  await point.focus(); await point.press('ArrowUp')
  await expect(curves.getByRole('spinbutton', { name: 'Point 2 output', exact: true })).toHaveValue('0.26')
  await curves.getByRole('button', { name: 'Remove point 2' }).click()
  await stack.getByRole('button', { name: 'Add color wheels', exact: true }).click()
  const wheels = page.getByLabel('Color wheels controls', { exact: true })
  const gainB = wheels.getByRole('spinbutton', { name: 'Gain B', exact: true })
  await gainB.fill('0.5'); await gainB.press('Enter')
  await expect.poll(() => gradingPixel(page)).toEqual([191, 64, 96, 255])
  const beforeEscape = await gradingSnapshot(page)
  await gainB.fill('2'); await gainB.press('Escape')
  expect((await gradingSnapshot(page)).past).toBe(beforeEscape.past)
  await expect(gainB).toHaveValue('0.5')
  const wheel = wheels.getByRole('slider', { name: 'Lift hue wheel', exact: true })
  await wheel.scrollIntoViewIfNeeded()
  const box = (await wheel.boundingBox())!, center = { x: box.x + box.width / 2, y: box.y + box.height / 2 }
  const beforeDrag = await gradingSnapshot(page)
  await page.mouse.move(center.x, center.y); await page.mouse.down(); await page.mouse.move(center.x + 24, center.y - 12, { steps: 4 })
  await expect.poll(async () => (await gradingSnapshot(page)).preview !== null).toBe(true)
  expect((await gradingSnapshot(page)).project).toEqual(beforeDrag.project)
  await page.mouse.up()
  const afterDrag = await gradingSnapshot(page)
  expect(afterDrag.past).toBe(beforeDrag.past + 1)
  expect(afterDrag.preview).toBeNull()
  const values = afterDrag.project.sequences[0].tracks[0].clips[0].effects.at(-1).params
  expect(values.liftR).toBeGreaterThan(0)
  expect(Math.abs(values.liftR + values.liftG + values.liftB)).toBeLessThan(1e-10)
  await page.evaluate(async () => { const d = '/src/state/documentStore.ts'; (await import(d)).useDocumentStore.getState().undo() })
  expect((await gradingSnapshot(page)).project).toEqual(beforeDrag.project)
  await page.evaluate(async () => { const d = '/src/state/documentStore.ts'; (await import(d)).useDocumentStore.getState().redo() })
  expect((await gradingSnapshot(page)).project).toEqual(afterDrag.project)
  await wheel.focus(); await wheel.press('Home')
  await expect(wheels.getByRole('spinbutton', { name: 'Lift R', exact: true })).toHaveValue('0')
  await wheel.press('ArrowRight')
  const keyed = await gradingSnapshot(page)
  expect(keyed.project.sequences[0].tracks[0].clips[0].effects.at(-1).params.liftR).toBeCloseTo(4 / 300)
  await wheels.getByText('Gain B animation', { exact: true }).click()
  await wheels.getByRole('button', { name: 'Animate Gain B', exact: true }).click()
  await page.evaluate(async () => { const t = '/src/state/transportStore.ts'; (await import(t)).useTransportStore.getState().setPlayheadFrame(10) })
  await gainB.fill('0.8'); await gainB.press('Enter')
  const animated = await gradingSnapshot(page), clip = animated.project.sequences[0].tracks[0].clips[0]
  expect(clip.animation.effectTracks.at(-1).keyframes.map((key: { frame: number }) => key.frame)).toEqual([1, 10])
  expect(clip.effects.at(-1).params.gainB).toBe(0.5)
  for (const width of [1280, 768]) {
    await page.setViewportSize({ width, height: 720 })
    const bounds = await wheels.evaluate((element) => ({ width: element.clientWidth, scroll: element.scrollWidth }))
    expect(bounds.scroll).toBeLessThanOrEqual(bounds.width + 1)
  }
  await page.setViewportSize({ width: 1280, height: 720 })
  await wheel.scrollIntoViewIfNeeded()
  await page.screenshot({ path: '/tmp/myrelith-196-grading-controls.png' })
  expect(problems).toEqual([])
})

test('native 33 LUT reuse, adjustment animation and static text/bus controls preserve their scopes', async ({ page }) => {
  const problems: string[] = []
  page.on('pageerror', (error) => problems.push(error.message))
  page.on('console', (message) => { if (['warning', 'error'].includes(message.type())) problems.push(message.text()) })
  await gradingProject(page)
  const bus = page.locator('.video-bus-inspector')
  await bus.getByText('Track and master video effects', { exact: true }).click()
  await bus.getByRole('button', { name: 'Add LUT…', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Choose LUT', exact: true })
  const before = await gradingSnapshot(page)
  await dialog.getByLabel('Local .cube file').setInputFiles({ name: 'bad.cube', mimeType: 'text/plain', buffer: Buffer.from('LUT_3D_SIZE 65\n0 0 0') })
  await expect(dialog.getByRole('alert')).toBeVisible()
  expect((await gradingSnapshot(page)).project).toEqual(before.project)
  const lines = ['TITLE "Native 33"', 'LUT_3D_SIZE 33']
  for (let b = 0; b < 33; b++) for (let g = 0; g < 33; g++) for (let r = 0; r < 33; r++) lines.push(`${r / 40} ${g / 32} ${b / 32}`)
  await dialog.getByLabel('Local .cube file').setInputFiles({ name: 'Native 33.cube', mimeType: 'text/plain', buffer: Buffer.from(lines.join('\n')) })
  await expect(dialog).toContainText('33 × 33 × 33, tetrahedral')
  await dialog.getByRole('button', { name: 'Apply imported LUT' }).click()
  const imported = await gradingSnapshot(page)
  expect(imported.project.colorLuts[0].size).toBe(33)
  expect(imported.past).toBe(before.past + 1)
  await expect(bus.getByText('Strength animation', { exact: true })).toHaveCount(0)
  await bus.getByLabel('Video effect target').selectOption(imported.project.sequences[0].tracks[0].id)
  await bus.getByRole('button', { name: 'Add color wheels' }).click()
  await bus.getByRole('spinbutton', { name: 'Gamma R', exact: true }).fill('1.2')
  await bus.getByRole('spinbutton', { name: 'Gamma R', exact: true }).press('Enter')
  await expect(bus.getByText('Gamma R animation', { exact: true })).toHaveCount(0)
  await bus.getByText('Track and master video effects', { exact: true }).click()
  await page.evaluate(async () => {
    const d = '/src/state/documentStore.ts', a = '/src/domain/adjustmentItems.ts', t = '/src/state/transportStore.ts'
    const store = (await import(d)).useDocumentStore, { createAdjustmentItem } = await import(a)
    const doc = store.getState().doc, item = createAdjustmentItem(0, 60, 'Grading adjustment')
    store.getState().insertAdjustment(doc.tracks[1].id, item)
    ;(await import(t)).useTransportStore.getState().setSelectedAdjustment(item.id)
  })
  const adjustment = page.getByTestId('adjustment-inspector')
  await adjustment.getByRole('button', { name: 'Add LUT…', exact: true }).click()
  await dialog.getByLabel('Embedded LUT', { exact: true }).selectOption({ label: 'Native 33 · 3D 33' })
  await dialog.getByRole('button', { name: 'Use embedded LUT' }).click()
  expect((await gradingSnapshot(page)).project.colorLuts).toHaveLength(1)
  await adjustment.getByRole('button', { name: 'Add color wheels' }).click()
  await adjustment.getByRole('spinbutton', { name: 'Lift R', exact: true }).fill('0.2')
  await adjustment.getByRole('spinbutton', { name: 'Lift R', exact: true }).press('Enter')
  await adjustment.getByText('Lift R animation', { exact: true }).click()
  await adjustment.getByRole('button', { name: 'Animate Lift R', exact: true }).click()
  const state = await gradingSnapshot(page), item = state.project.sequences[0].tracks[1].adjustments[0]
  expect(item.animation.effectTracks[0]).toMatchObject({ parameter: 'liftR', keyframes: [{ frame: 1, value: 0.2, easing: { type: 'linear' } }] })
  await page.evaluate(async () => {
    const d = '/src/state/documentStore.ts', o = '/src/domain/operations.ts', t = '/src/state/transportStore.ts'
    const store = (await import(d)).useDocumentStore, doc = store.getState().doc
    const clip = (await import(o)).createTextClip(doc, 0, 60, 'Title')
    store.getState().insertClips([{ trackId: doc.tracks[2].id, clip }])
    ;(await import(t)).useTransportStore.getState().setSelectedClip(clip.id)
  })
  await page.getByRole('tab', { name: 'Effects', exact: true }).click()
  const clipStack = page.getByRole('region', { name: 'Effect stack', exact: true })
  await clipStack.getByRole('button', { name: 'Add RGB curves' }).click()
  await expect(clipStack.getByText('Strength animation', { exact: true })).toHaveCount(0)
  expect(problems).toEqual([])
})
